name: RAG CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run notebook
      run: |
        pip install nbconvert jupyter
        jupyter nbconvert --to notebook --execute notebooks/RETO_RAG.ipynb --output output.ipynb

    - name: Upload executed notebook
      uses: actions/upload-artifact@v3
      with:
        name: executed-notebook
        path: output.ipynb
